//                                  !! RAM !!

/*
 * MainFrame.java
 *
 * Created on July 17, 2008, 2:23 PM
 */
package tts.ui;

import java.util.prefs.Preferences;

/**
 *
 * @author Sumit Shrestha
 */
public class MainFrame extends javax.swing.JFrame implements tts.domain.FrameInterface {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.loadSavedAudioProfile();
        this.setFrameIcon();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PlayBtn = new javax.swing.JButton();
        StopBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pauseBtn = new javax.swing.JButton();
        audioProfileLabel = new javax.swing.JLabel();
        profileCombo = new javax.swing.JComboBox<>();
        profileStatusLabel = new javax.swing.JLabel();
        centralPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InputText = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sumit's Nepali TTS");
        setResizable(false);

        PlayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tts/ui/img/play.png"))); // NOI18N
        PlayBtn.setToolTipText("Play");
        PlayBtn.setBorder(null);
        PlayBtn.setBorderPainted(false);
        PlayBtn.setContentAreaFilled(false);
        PlayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayBtnActionPerformed(evt);
            }
        });

        StopBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tts/ui/img/stop.png"))); // NOI18N
        StopBtn.setToolTipText("Stop");
        StopBtn.setBorder(null);
        StopBtn.setBorderPainted(false);
        StopBtn.setContentAreaFilled(false);
        StopBtn.setEnabled(false);
        StopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopBtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tts/ui/img/logo.png"))); // NOI18N

        pauseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tts/ui/img/pause.png"))); // NOI18N
        pauseBtn.setToolTipText("Pause");
        pauseBtn.setBorder(null);
        pauseBtn.setBorderPainted(false);
        pauseBtn.setContentAreaFilled(false);
        pauseBtn.setEnabled(false);
        pauseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseBtnActionPerformed(evt);
            }
        });

        audioProfileLabel.setText("Audio:");

        profileCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "crisp", "balanced", "smooth" }));
        profileCombo.setSelectedItem(Player.getProfile().name().toLowerCase());
        profileCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileComboActionPerformed(evt);
            }
        });

        profileStatusLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        profileStatusLabel.setText("Profile: balanced");
        updateProfileStatusLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PlayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pauseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(audioProfileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profileStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3)
                .addComponent(PlayBtn)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pauseBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StopBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(audioProfileLabel)
                        .addComponent(profileCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profileStatusLabel))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        centralPanel.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setResizeWeight(1.0);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Short Cuts");
        jPanel2.add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tts/ui/img/FontInfo.png"))); // NOI18N
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        InputText.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(InputText);

        jSplitPane1.setLeftComponent(jScrollPane1);

        centralPanel.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(centralPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayBtnActionPerformed
        if (this.presentPlayerWorker != null) {
            this.presentPlayerWorker.play();
        } else {
            this.presentPlayerWorker = new tts.domain.Player(InputText, Player, this);
            this.presentPlayerWorker.execute();
        }
        this.StopBtn.setEnabled(true);
        this.PlayBtn.setEnabled(false);
        this.pauseBtn.setEnabled(true);
        this.InputText.requestFocusInWindow();
}//GEN-LAST:event_PlayBtnActionPerformed

    private void StopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopBtnActionPerformed
        this.presentPlayerWorker.cancel(true);
        this.presentPlayerWorker = null;
        this.StopBtn.setEnabled(false);
        this.PlayBtn.setEnabled(true);
        this.pauseBtn.setEnabled(false);
    }//GEN-LAST:event_StopBtnActionPerformed

    private void pauseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseBtnActionPerformed
        if (!this.presentPlayerWorker.isPaused()) {
            this.presentPlayerWorker.pause();
            this.PlayBtn.setEnabled(true);
            this.pauseBtn.setEnabled(false);
        }
}//GEN-LAST:event_pauseBtnActionPerformed

    private void profileComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileComboActionPerformed
        Object selected = this.profileCombo.getSelectedItem();
        if (selected instanceof String s) {
            var profile = tts.domain.TTSEngine.AudioProfile.from(s);
            this.Player.setProfile(profile);
            this.prefs.put(PREF_AUDIO_PROFILE, profile.name().toLowerCase());
            updateProfileStatusLabel();
        }
    }//GEN-LAST:event_profileComboActionPerformed

    private void loadSavedAudioProfile() {
        var saved = this.prefs.get(PREF_AUDIO_PROFILE, this.Player.getProfile().name().toLowerCase());
        var profile = tts.domain.TTSEngine.AudioProfile.from(saved);
        this.Player.setProfile(profile);
        this.profileCombo.setSelectedItem(profile.name().toLowerCase());
        updateProfileStatusLabel();
    }

    private void updateProfileStatusLabel() {
        var currentProfile = this.Player.getProfile().name().toLowerCase();
        this.profileStatusLabel.setText("Profile: " + currentProfile);
    }

    private void setFrameIcon() {
        java.awt.Image im = java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/tts/ui/img/nepal.png"));
        this.setIconImage(im);
    }

    @Override
    public void onPlayCompletion(final String state) {
        this.InputText.setCaretPosition(0);
        this.presentPlayerWorker = null;
        this.PlayBtn.setEnabled(true);
        this.StopBtn.setEnabled(false);
        this.pauseBtn.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane InputText;
    private javax.swing.JButton PlayBtn;
    private javax.swing.JButton StopBtn;
    private javax.swing.JLabel audioProfileLabel;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton pauseBtn;
    private javax.swing.JComboBox<String> profileCombo;
    private javax.swing.JLabel profileStatusLabel;
    // End of variables declaration//GEN-END:variables
    private static final String PREF_AUDIO_PROFILE = "audio.profile";
    private final Preferences prefs = Preferences.userNodeForPackage(MainFrame.class);
    private tts.domain.TTSEngine Player = new tts.domain.TTSEngine();
    private tts.domain.Player presentPlayerWorker;
}
